hosted-zone = "hashidemos.io"
namespace = "pphan"
owner = "pphan@hashicorp.com"
create_aws_dns_zone = "true"
create_azure_dns_zone = "false"
create_gcp_dns_zone = "true"

# aws_region = "us-west-2"
# azure_location = "us-west"
gcp_region = "us-west"
gcp_project = "pphan-test-app-dev"
